backend:
  name: github
  repo: ouroakley/main
  branch: main
  site_domain: https://www.ouroakley.uk
  base_url: https://www.ouroakley.uk
  auth_endpoint: /api/auth
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "events"
    label: "Events"
    label_singular: "Event"
    folder: "content/events"
    create: true
    nested:
      depth: 100
      summary: '{{title}}'
    meta:
      path:
        widget: string
        label: 'Path'
        index_file: 'index'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Event Start", name: "eventStart", widget: "datetime"}
      - {label: "Event End", name: "eventEnd", widget: "datetime", required: false}
      - label: "Venues"
        name: "venues"
        widget: "relation"
        collection: "venues"
        search_fields: ["title", "address"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        multiple: true
      - label: "Organisers"
        name: "organisers"
        widget: "relation"
        collection: "organisers"
        search_fields: ["title", "fullName"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        multiple: true
      - {label: "Content", name: "body", widget: "markdown"}

  - name: "venues"
    label: "Venues"
    label_singular: "Venue"
    folder: "content/venues"
    create: true
    nested:
      depth: 100
      summary: '{{title}}'
    meta:
      path:
        widget: string
        label: 'Path'
        index_file: '_index'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Address", name: "address", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown", required: false}

  - name: "organisers"
    label: "Organisers"
    label_singular: "Organiser"
    folder: "content/organisers"
    create: true
    nested:
      depth: 100
      summary: '{{title}}'
    meta:
      path:
        widget: string
        label: 'Path'
        index_file: '_index'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Full Name", name: "fullName", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Contact Email", name: "contact", widget: "string", required: false}
      - {label: "Website", name: "website", widget: "string", required: false}
      - {label: "Content", name: "body", widget: "markdown", required: false}
