backend:
  name: github
  repo: ouroakley/main
  branch: main
  site_domain: https://www.ouroakley.uk
  base_url: https://www.ouroakley.uk
  auth_endpoint: /api/auth
  squash_merges: true

editor:
  preview: false

publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "events"
    label: "Events"
    label_singular: "Event"
    folder: "content/events"
    create: true
    summary: "{{title}} - {{eventStart | date('DD MMM YYYY')}}"
    nested:
      depth: 5
      summary: '{{dirname}}'
      subfolders: false
    view_groups:
      - label: "Venue"
        field: venues
      - label: "Organiser"
        field: organisers
    meta:
      path:
        widget: string
        label: 'Path'
        index_file: 'index'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - label: "Event Dates"
        name: "eventDates"
        widget: "list"
        required: false
        hint: "Add multiple dates for recurring or multi-day events"
        fields:
          - {label: "Start Date", name: "start", widget: "datetime"}
          - {label: "End Date", name: "end", widget: "datetime"}
      - {label: "Event Start (Legacy)", name: "eventStart", widget: "datetime", required: false, hint: "Use Event Dates above for multi-day events"}
      - {label: "Event End (Legacy)", name: "eventEnd", widget: "datetime", required: false, hint: "Use Event Dates above for multi-day events"}
      - label: "Venues"
        name: "venues"
        widget: "relation"
        collection: "venues"
        search_fields: ["title", "address"]
        value_field: "{{title}}"
        display_fields: ["title"]
        multiple: true
      - label: "Organisers"
        name: "organisers"
        widget: "relation"
        collection: "organisers"
        search_fields: ["title", "fullName"]
        value_field: "{{title}}"
        display_fields: ["title"]
        multiple: true
      - {label: "Content", name: "body", widget: "markdown", required: false}

  - name: "venues"
    label: "Venues"
    label_singular: "Venue"
    folder: "content/venues"
    create: true
    nested:
      depth: 100
      summary: '{{title}}'
    meta:
      path:
        widget: string
        label: 'Path'
        index_file: '_index'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Address", name: "address", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown", required: false}
      - label: "Allowed Editors"
        name: "allowed_editors"
        widget: "list"
        required: false
        hint: "Editors that can add additional information about this venue"

  - name: "organisers"
    label: "Organisers"
    label_singular: "Organiser"
    folder: "content/organisers"
    create: true
    nested:
      depth: 100
      summary: '{{title}}'
    meta:
      path:
        widget: string
        label: 'Path'
        index_file: '_index'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Full Name", name: "fullName", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown", required: false}
      - label: "Allowed Editors"
        name: "allowed_editors"
        widget: "list"
        required: false
        hint: "Editors that can add additional information about this organiser"
